# Generated by Django 6.0.6 on 2026-07-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('entity_type', models.CharField(choices=[('Individual', 'Individual'), ('Organization', 'Organization')], max_length=50)),
                ('date_added', models.DateField()),
                ('program', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
